version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./ECOMM-v1/ECOMM/:/var/www/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - alpha
    depends_on:
      - php
    restart: on-failure

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 20s
      retries: 6
      start_period: 5s
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: on-failure
    networks:
      - alpha

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
#    image: app-php
#    volumes:
#      - ./ECOMM-v1/ECOMM/:/usr/share/nginx/html/
    networks:
      - alpha

  phpmyadmin:
    image: phpmyadmin:5.2.2
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - alpha

networks:
  alpha:
    driver: bridge
